name: liveforspeed
title: Live For Speed (WINE)
version: 'S3-7A'
summary: Live for Speed (LFS) is a online racing simulator
description: |
 Live for Speed is a serious racing simulator. No arcade modes, no steering aids - YOU have to do the driving.

 The forces affecting the car's motion are simulated individually at each wheel. We recommend the use of a steering wheel, because although you can use the keyboard and/or mouse, a wheel and pedals provide a lot more accuracy. The force feedback sent to the steering wheel is calculated directly from the forces, with no canned effects. This allows you to feel what is happening at the contact patch between your tyres and the road, helping you to get closer to the limit without exceeding it too much!

 When you have a lot of speed and you approach a corner, you must brake well in advance or you will end up somewhere you don't want to be! You need to find the best way through any sequence of bends by going through them many times. There's always more to learn.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    run-on: [amd64, i386]
base: core18
compression: lzo

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-6-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-6-stable

environment:
  WINEDLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko
  WINEPREFIX: "$SNAP_USER_COMMON/.wine"
  WINEARCH: "win32"
  INSTALL_URL: "https://www.lfs.net/download/LFS_S3_7A_setup.exe"
  INSTALL_FLAGS: "/S"
  RUN_EXE: "C:/LFS/LFS.exe"
  NO_AT_BRIDGE: "1" # Fix yad error Failed to connect to socket /tmp/dbus-xxx: No such file or directory
  DISABLE_WAYLAND: "1" # Fix gtk decoration under wayland session
  SYSTEM_WGETRC: $SNAP/wine-runtime/etc/wgetrc

apps:
  liveforspeed:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    plugs:
      - home
      - joystick
      - network
      - network-bind
      - opengl
      - audio-playback
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier
    plugs:
      - home
      - network
  # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  liveforspeed:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      snapcraftctl build
      set -ex
      mkdir -p sommelier/hooks ; cp -R -p sommelier $SNAPCRAFT_PART_INSTALL
    stage:
      - sommelier

  # The sommelier script helps you snap Windows applications using Wine. It
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/mmtrt/sommelier-core.git
    source-branch: "tmp"
